### ISSUE TITLE
I have one CSS related issue...

### ISSUE THREAD

**Issue by mirzatalat** [pisi/Reel#221]
...and i know u'll answer me to the point ;) :- I am trying to place four buttons inside a circular div , its working fine on firefox , but not on chrome(buttons are misplaced/scattered)  here is the code i for CSS:

``` css
.Circle_Base {
-webkit-border-radius: 999px; /*circular base for div*/
-moz-border-radius: 999px;
border-radius: 999px;
behavior: url(PIE.htc);
}

.type1{
width: 100px;
height: 100px;                   /* div */
background: #ecf0f1;
border: 1px solid black;
margin-left:25%;
margin-top:10%;
}

#button-up{
float:left;                     /* button-Up */
margin-left: 33px;
margin-top: 6px;
}

#button-right{                
float:left;                   /* button-right */
margin-left: 15px;
margin-top: 10px;  
}

#button-left{  
float:left;                  /* button-left */
margin-left: 10px;
margin-top: 9px;
}

#button-down{
float:left;             /* down button*/
margin-left: 33px;
margin-top: 7px;
}
```
